AWSTemplateFormatVersion: '2010-09-09'
Description: WordPress Compute Stack

Resources:

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-xxxxxxxx
      InstanceType: t2.micro

      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install php8.0 -y
          yum install httpd php php-mysqlnd wget -y

          systemctl start httpd
          systemctl enable httpd

          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          cp -r wordpress/* /var/www/html/

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    