name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Repository Files
        run: |
          pwd
          ls -R

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Network Stack
        run: |
          aws cloudformation deploy \
          --stack-name wordpress-network \
          --template-file networkstack.yaml

      - name: Deploy Database Stack
        run: |
          aws cloudformation deploy \
          --stack-name wordpress-database \
          --template-file databasestack.yaml

      - name: Deploy Compute Stack
        run: |
          aws cloudformation deploy \
          --stack-name wordpress-compute \
          --template-file computestack.yaml

      - name: Deploy Monitoring Stack
        run: |
          aws cloudformation deploy \
          --stack-name wordpress-monitoring \
          --template-file monitoringstack.yaml
